### PR TITLE
Us 1232218 bug fixing

### PR DESCRIPTION
**Pull request by v-pomanv**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C4%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201806040457456378-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7rUs0iWTSKNSLl21hlVPC7cEZ4QeLOcgGDW6SDklMUk%3D&st=2018-06-04T04%3A53%3A48Z&se=2018-07-05T04%3A58%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-pomanv** [comment]
page updated

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C4%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201806040525209285-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CDDd384R%2FltKAD%2B4seeFu6VsnZf31Suai4NzC71SNCw%3D&st=2018-06-04T05%3A21%3A52Z&se=2018-07-05T05%3A26%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C4%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201806040532195920-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BxQip6CsB6saC6nDK1Tk7k8GzgKx%2FVITx7cSXYg5hBo%3D&st=2018-06-04T05%3A28%3A22Z&se=2018-07-05T05%3A33%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C4%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201806040533214951-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RQw9D4FJLzDL5FN8lHlQt%2FImxr6MXuzLjpAk5ckWbr4%3D&st=2018-06-04T05%3A29%3A46Z&se=2018-07-05T05%3A34%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C4%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201806040555482440-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=elI6PF2MwJ2t8Org5vE4WYZwILW3gVc%2BjsnpqY7r8yE%3D&st=2018-06-04T05%3A51%3A52Z&se=2018-07-05T05%3A56%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-zh-tw-2) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-zh-tw-2) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/v-pomanv/OfficeDocs-OfficeOnlineServer-Test-loc-pr.zh-tw/blob/US_1232218_Bug_fixing/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-tw/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-zh-tw-2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C7%5C2521e7de-8afb-3835-0193-4a1dc9478891%5CPullRequest%5C201807070056496784-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lUWJJMjXMtN%2BHFuPe8ZHTS5QisrQK%2BtRIGl3in7%2BgBw%3D&st=2018-07-07T00%3A52%3A56Z&se=2018-08-07T00%3A57%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
